---
include:
  - board: pro_micro
    shield: cygnus_left
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: cygnus_left_pro_micro
  - board: pro_micro
    shield: cygnus_right
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: cygnus_right_pro_micro
